packages:
  - packages/*

forceLegacyDeploy: true
minimumReleaseAge: 1440

onlyBuiltDependencies:
  - "@dashevo/protobufjs"
  - "@tailwindcss/oxide"
  - cpu-features
  - esbuild
  - fsevents
  - microtime
  - protobufjs
  - sharp
  - ssh2

peerDependencyRules:
  ignoreMissing:
    - canvas

resolvePeersFromWorkspaceRoot: true

strictPeerDependencies: false

supportedArchitectures:
  cpu: [x64, arm64]
  libc: [glibc, musl]
  os: [linux, current]
