packages:
  - packages/*

forceLegacyDeploy: true
minimumReleaseAge: 1440

peerDependencyRules:
  ignoreMissing:
    - canvas

resolvePeersFromWorkspaceRoot: true

strictPeerDependencies: false

supportedArchitectures:
  cpu: [x64, arm64]
  libc: [glibc, musl]
  os: [linux, current]
