packages:
  - packages/*

forceLegacyDeploy: true

onlyBuiltDependencies:
  - '@dashevo/protobufjs'
  - '@tailwindcss/oxide'
  - core-js
  - cpu-features
  - esbuild
  - fsevents
  - microtime
  - protobufjs
  - sharp
  - ssh2

overrides:
  '@vibescraper/website>@types/node': npm:@types/web@latest
  '@vibescraper/website>@types/node-legacy': npm:@types/node@latest
  '@vibescraper/website>@typescript/lib-dom': npm:@types/web@latest

peerDependencyRules:
  ignoreMissing:
    - canvas

resolvePeersFromWorkspaceRoot: true

strictPeerDependencies: false

supportedArchitectures:
  cpu: [x64, arm64]
  libc: [glibc, musl]
  os: [linux, current]
